Update bugger

diff --git a/bugger b/bugger
--- a/bugger
+++ b/bugger
@@ -77,31 +77,9 @@ take_screenshot() {
 
 # Function to start screen recording
 start_screen_recording() {
-    echo "Starting screen recording..."
-    adb -s "$DEVICE_SERIAL" shell screenrecord $video_filename &
-    record_pid=$!
-    
-    read -p "Tap x to stop screen recording : " response
+    #!/bin/bash
 
-if [[ "$response" == "x" ]]; then
-    echo "Stopping screen recording and saving the video in system"
-    adb -s "$DEVICE_SERIAL" shell pkill -SIGINT screenrecord
-    sleep 5
-    adb -s "$DEVICE_SERIAL" pull $video_filename . > /dev/null
-    echo "Recording saved as $video_filename"
-    exit 1
-   
-else
-    echo -e "${RED}Exiting script.${NC}"
-    exit 1
-    
-    fi
-    
-}
-startrecord(){
-#!/bin/bash
-
-echo "Do you want to start screen recording and logcat? (y/n): "
+echo "Do you want to start screen recording (y/n): "
 read -p "" start_confirmation
 
 if [[ $start_confirmation == "y" ]]; then
@@ -113,10 +91,7 @@ else
     exit 0
 fi
 
-
-
-    }
-
+}
 
 # Function to stop screen recording
 stop_screen_recording() {
@@ -132,27 +107,8 @@ start_logcat() {
     echo "Starting logcat..."
     adb -s "$DEVICE_SERIAL" logcat > $log_filename 2>&1 &
     logcat_pid=$!
-    
- read -p "Tap x to stop logcat : " response
 
-if [[ "$response" == "x" ]]; then
-echo "Stopping logcat..."
-    kill -9 $logcat_pid
-    echo "Logcat saved as $log_filename"
-    exit 1
-    
-    else
-    echo -e "${RED}Exiting script.${NC}"
-    exit 1
-    fi
 }
-
-logcat(){
-    echo "Starting logcat..."
-    adb -s "$DEVICE_SERIAL" logcat > $log_filename 2>&1 &
-    logcat_pid=$!
-    }
-
 
 # Function to stop logcat
 stop_logcat() {
@@ -169,74 +125,92 @@ generate_bug_report() {
     echo "Bug report saved as bugreport_$timestamp.txt"
     exit 1
 }
-Crossreboot_logs(){
-echo "Started cross reboot logs"
 
-while true; do adb logcat | tee -a crosslogs.txt;
+# Function to start cross reboot logs
+cross_reboot_logs() {
+    echo "Started cross reboot logs"
+    printf "\033[0;31mCtrl+c\033[0m %s to stop cross reboot logs.\n"
+   while true; do adb -s "$DEVICE_SERIAL" logcat | tee -a crosslogs.txt;
 echo "==========REBOOT============" >>   crosslogs.txt;
 done > /dev/null 2>&1
 
+  
 }
 
-while true; do
+# Device_Info
+Device_info() {
+ Device_fingerprint=$(adb -s "$DEVICE_SERIAL" shell getprop | grep ro.build.fingerprint)
+            Android_Version=$(adb -s "$DEVICE_SERIAL" shell getprop ro.build.version.release)
+            Playstore_version=$(adb -s "$DEVICE_SERIAL" shell dumpsys package com.android.vending | grep versionName | head -1 | cut -d'=' -f2)
+            hardware_version=$(adb -s "$DEVICE_SERIAL" shell getprop ro.boot.hardware.revision)
+            sdk_version=$(adb -s "$DEVICE_SERIAL" shell getprop ro.build.version.sdk)
+            printf "\033[0;31mDevice Fingerprint:\033[0m %s\n" "$Device_fingerprint"
+            printf "\033[0;31mAndroid Version:\033[0m %s\n" "$Android_Version"
+            printf "\033[0;31mPlaystore Version:\033[0m %s\n" "$Playstore_version"
+            printf "\033[0;31mSDK Version:\033[0m %s\n" "$sdk_version"
+            printf "\033[0;31mHardware Version:\033[0m %s\n" "$hardware_version"
+           
+}
+
 # Main menu for user selection
+while true; do
     echo "Select the action to perform:"
     echo "1) Screen Recording"
     echo "2) Take Screenshot"
     echo "3) Cross reboot logs"
-    echo "4) logcat"
+    echo "4) Logcat"
     echo "5) Bug Report"
     echo "6) Show Device Info"
-    echo "7) Collect (Screen Recording,Screenshot, Logcat, Bug Report)Together"
+    echo "7) Collect (Screen Recording, Screenshot, Logcat, Bug Report) Together"
     echo "8) Exit"
 
     read -p "Enter your choice (1-8): " choice
     case $choice in
         1)
             start_screen_recording
-            ;;
-        3)
-            Crossreboot_logs
-            ;;
-        4)
-            start_logcat
+            printf "Tap \033[0;31m'x'\033[0m to stop Screen recording.\n"
+            read -r -n1 key
+            if [[ $key == "x" ]]; then
+                stop_screen_recording
+                exit 1
+            else
+                echo -e "${RED}Invalid input. Exiting.${NC}"
+                exit 1
+            fi
             ;;
         2)
             take_screenshot
             ;;
+        3)
+            cross_reboot_logs
+            ;;
+        4)
+            start_logcat
+            printf "Tap \033[0;31m'x'\033[0m to Stop Logcat.\n"
+            read -r -n1 key
+            if [[ $key == "x" ]]; then
+                stop_logcat
+                exit 1
+            else
+                echo -e "${RED}Invalid input. Exiting.${NC}"
+                exit 1
+            fi
+            ;;
         5)
             generate_bug_report
-            ;;
-        6)
-            Device_fingerprint=$(adb -s "$DEVICE_SERIAL" shell getprop | grep ro.build.fingerprint)
-            Android_Version=$(adb -s "$DEVICE_SERIAL" shell getprop ro.build.version.release)
-            Playstore_version=$(adb -s "$DEVICE_SERIAL" shell dumpsys package com.android.vending | grep versionName | head -1 | cut -d'=' -f2)
-            hardware_version=$(adb -s "$DEVICE_SERIAL" shell getprop ro.boot.hardware.revision)
-            sdk_version=$(adb -s "$DEVICE_SERIAL" shell getprop ro.build.version.sdk)
-            printf "\033[0;31mDevice Fingerprint:\033[0m %s\n" "$Device_fingerprint"
-            printf "\033[0;31mAndroid Version:\033[0m %s\n" "$Android_Version"
-            printf "\033[0;31mPlaystore Version:\033[0m %s\n" "$Playstore_version"
-            printf "\033[0;31mSDK Version:\033[0m %s\n" "$sdk_version"
-            printf "\033[0;31mHardware Version:\033[0m %s\n" "$hardware_version"
-            
             exit 1
             ;;
-        7)
-           
-Device_fingerprint=$(adb -s "$DEVICE_SERIAL" shell getprop | grep ro.build.fingerprint)
-            Android_Version=$(adb -s "$DEVICE_SERIAL" shell getprop ro.build.version.release)
-            Playstore_version=$(adb -s "$DEVICE_SERIAL" shell dumpsys package com.android.vending | grep versionName | head -1 | cut -d'=' -f2)
-            hardware_version=$(adb -s "$DEVICE_SERIAL" shell getprop ro.boot.hardware.revision)
-            sdk_version=$(adb -s "$DEVICE_SERIAL" shell getprop ro.build.version.sdk)
-            printf "\033[0;31mDevice Fingerprint:\033[0m %s\n" "$Device_fingerprint"
-            printf "\033[0;31mAndroid Version:\033[0m %s\n" "$Android_Version"
-            printf "\033[0;31mPlaystore Version:\033[0m %s\n" "$Playstore_version"
-            printf "\033[0;31mSDK Version:\033[0m %s\n" "$sdk_version"
-            printf "\033[0;31mHardware Version:\033[0m %s\n" "$hardware_version"
+        6)
+            Device_info
+            exit 1
+            ;;
+          7)
+          
 
-startrecord
-logcat
-printf "Tap \033[0;31m's'\033[0m to take a screenshot.\n"
+Device_info
+start_screen_recording
+start_logcat
+ printf "Tap \033[0;31m's'\033[0m to take a screenshot.\n"
 printf "Tap \033[0;31m'x'\033[0m to stop Screen recording and Logcat.\n"
 
 while true; do
@@ -254,6 +228,7 @@ while true; do
         if [[ $start_confirmation == "y" ]]; then
             trap 'exit' INT
             generate_bug_report
+            exit 1
         else
             exit 1
         fi
@@ -265,7 +240,6 @@ done
             ;;
         8)
             echo "Exiting."
-            # Make sure to stop any background processes
             pkill -f screenrecord
             pkill -f logcat
             exit 0
@@ -274,4 +248,3 @@ done
             echo "Invalid selection. Please try again."
             ;;
     esac
-done
